### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by mikeerickson** [valet-lite/beta#14]
Hey there,

Running into an issue on the test site I configured.  

After activating the site via app, I visited "hello.test" (this is a barebones new l8 app I just created)

![image](https://user-images.githubusercontent.com/183153/95522605-5d8ec180-0981-11eb-8f7e-c21aaafa596a.png)

**Comment by davidhemphill** [comment]
It looks like your site is hitting an Nginx server, which Valet Lite doesn’t use. Do you have the Valet CLI tool or any other servers running?

**Comment by davidhemphill** [comment]
Closing for now since we don't nginx servers (we use Caddy). 😃

**Comment by mikeerickson** [comment]
I don’t have any preference as far as web server is concerned. I guess I will have to figure out how to disable this.
