### ISSUE TITLE
Domain does not resolve

### ISSUE THREAD

**Issue by eboye** [valet-lite/beta#16]
Hi,

I just installed the app (from second email), made the app, started it and the test domain does not resolve.

I'm using apache via homebrew but manually mapping the .local domains via /etc/hosts so that shouldn't be it.

I haven't used .test domains at all.

Should I enable something?

**Comment by eboye** [comment]
Hmm, it may be the [gasmask](https://github.com/2ndalpha/gasmask) app

![image](https://user-images.githubusercontent.com/624357/95528140-922d6800-09d7-11eb-9d67-ebc4bf41eb16.png)

I have a pretty big /etc/hosts file. Should I backup first before I disable this restoring feature?

**Comment by davidhemphill** [comment]
Hmm...it's hard to say without using the app, but it does look like Gasmask could be clobbering the entries Valet Lite puts in `/etc/hosts`.

**Comment by davidhemphill** [comment]
@eboye Can you try disabling Gasmask and see if it resolves the issue? Can reopen it if you continue to have issues. Thanks!

**Comment by eboye** [comment]
I've disabled the Gasmask app and valet indeed adds the domain to /etc/hosts

But it then maps to the localhost which is httpd installed via brew.

I should disable that as well I suppose as valet and httpd are listening at port 80?

If that's the case, I think valet should inform the user that it cannot start on port 80 as other service is using it.
