### ISSUE TITLE
Site wont load as `valet.test` but will load if supplying port `valet.test:9000`

### ISSUE THREAD

**Issue by mikeerickson** [valet-lite/beta#17]
I am making progress :-)

I have worked out the `nginx` issue and am now receiving the typical site can't be reached (see image below).  
If I hit `valet.test:9000` (or whatever the reported IP address is in the log) all works as expected

Further, I can ping `valet.test` and it responds.

Sorry for the "lame" question, but my overall OPS skills are "lacking" :-)

![image](https://user-images.githubusercontent.com/183153/95599039-704ada00-0a05-11eb-9425-16e788f2453c.png)

Note: `valet.test` is just a test L8 app I have created
===

**Comment by davidhemphill** [comment]
Can you post the contents of the following items:

- Caddy log (Menu > Logs > Show Caddy server log in browser), 
- The contents of `etc/hosts` file, 
- Your Caddyfile `~/Library/Application Support/Valet Lite/Caddyfile, 
- And your config `~/Library/Application Support/Valet Lite/config.json`

That'll help a ton in debugging the situation. Thanks!

**Comment by mikeerickson** [comment]
Here you go

Caddy Log

```json
{"level":"info","ts":1602255013.93933,"msg":"using provided configuration","config_file":"/Users/mikee/Library/Application Support/Valet Lite/Caddyfile","config_adapter":""}
run: adapting config using caddyfile: parsing caddyfile tokens for 'log': /Users/mikee/Library/Application Support/Valet Lite/Caddyfile:25 - Error during parsing: Wrong argument count or unexpected line ending after 'file'
```

etc/hosts

```
 127.0.0.1 valet.test
```

Caddyfile

```
http://valet.test {
  reverse_proxy localhost:9000

  log {
    output file /Users/mikee/.lite/log/valet.test.log 
    format console
    level INFO
  }
}
```

config.json

```json
{
	"caddyProcessId": 20420,
	"activated": true,
	"licenseKey": "HYQA-VFVZ-9HLW-VYQG-ZFXX",
	"installed": true,
	"sites": [
		{
			"uuid": "7d63ec10-0a3f-11eb-912e-298980788647",
			"name": "valet",
			"path": "/Users/mikee/Documents/code/litterbox/valet",
			"isRunning": true,
			"port": 9000,
			"tld": "test",
			"url": "http://valet.test",
			"processId": 29560,
			"type": "laravel",
			"logPath": "/Users/mikee/.lite/log/valet.test.log"
		}
	],
	"phpVersion": "7.3.20",
	"caddyTrusted": true,
	"openSiteInBrowserWhenStarting": true,
	"defaultTLD": "test"
}
```

**Comment by davidhemphill** [comment]
My guess is the Caddy server is not initializing correctly. Can you confirm when you start a site that a `caddy` process is running inside Activity Monitor?

**Comment by mikeerickson** [comment]
Hey David

There is no `caddy` service running when I have started one of the items in `Valet Lite`

**Comment by dannegrun** [comment]
Hi! 

I have the same problem, but I get "404 - not found" when I'm not adding :9000. With :9000 the site is shown. It's a Laravel 8 site. No Caddy service is running for me either.

The menu for me is showing Logs -> Show Caddy server log in Finder, but nothing happens when I click it. I don't have the folder .lite in my home path that the config.json set. I have version 0.1.32.

I have the same hosts (except with my domain name) and Caddyfile files but my config.json don't have the rows:
"phpVersion": "7.3.20",
"openSiteInBrowserWhenStarting": true,
"defaultTLD": "test"

Thanks!

**Comment by Dixens** [comment]
Hey David,

Thanks for this very nice beta!

We also have this issue: can't connect to valet.test but OK for valet.test:9001 (not 9000)

```
{"level":"info","ts":1602582141.186962,"msg":"using provided configuration","config_file":"/Users/dixens/Library/Application Support/Valet Lite/Caddyfile","config_adapter":""}
run: adapting config using caddyfile: parsing caddyfile tokens for 'log': /Users/dixens/Library/Application Support/Valet Lite/Caddyfile:5 - Error during parsing: Wrong argument count or unexpected line ending after 'file'
``` 

Note the following bit @mikeerickson [mentioned](https://github.com/valet-lite/beta/issues/17#issuecomment-706768621):

```
Error during parsing: Wrong argument count or unexpected line ending after 'file'
```

Thanks

**Comment by davidhemphill** [comment]
So the reason `domain.test:9001` (or similar) works is because your domain name is added to `/etc/hosts`, pointing to localhost. So it's essentially the same as if you visited `127.0.0.1:9000`, which is working for everyone. I've not been able to replicate the issue yet, but it definitely seems like Caddy isn't starting for some reason, even though the Caddyfile appears to be correct. Will keep looking. :-)

**Comment by Dixens** [comment]
Thank you David :-) (No problem for 9000 vs 9001, of course)

**Comment by underwood** [comment]
I was having a similar issue.

I resolved it by in the terminal using

`valet stop`

To stop my locally running valet, then removed all my sites from valet lite, added them again and when I started them I was able to view them at project.test as expected.

**Comment by mikeerickson** [comment]
@underwood hmmm, I don’t believe I have it installed (prior to Valet lite) but I will have a closer look.  Thank you for the information

**Comment by Dixens** [comment]
Thank you @underwood We don't have Valet installed either.

**Comment by underwood** [comment]
@mikeerickson @Dixens ok, you guys have a different issue.

You could try changing the settings domain from .test to .example (I was just changing it to something different to see if it would refresh settings under the hood)

Then removing and re-adding a site to valet lite. 

Then restarting that site in valet lite.

That seemed to clear up issues for me for the site only displaying when I used the IP+port in the log.

It was running normally on my macbook just installed it and it worked, on my mac is where I was having issues with not being able to view it at the expected domain.

**Comment by davidhemphill** [comment]
If you have an existing web server running, Valet Lite will not be able to handle DNS requests on port 80. :-)
