### ISSUE TITLE
404 Not Found using Domain TLD

### ISSUE THREAD

**Issue by mrchrisoliver** [valet-lite/beta#18]
Currently testing Valet Lite, I have a Laravel app, when I used appname.example(or any TLD but .test) I get a white page with "404 - Not Found". If I "Open PHP Server in browser" it works. Will this be a general bug or is it because I have Laravel Valet already installed? Laravel Valet is using .test for its domain.

**Comment by davidhemphill** [comment]
Usually, Valet Lite won't show a 404 (that means it's hitting a server somewhere), but will usually white screen. Can you post these items:

- Caddy log (Menu > Logs > Show Caddy server log in browser), 
- The contents of `etc/hosts` file, 
- Your Caddyfile `~/Library/Application Support/Valet Lite/Caddyfile, 
- And your config `~/Library/Application Support/Valet Lite/config.json`

Thanks!

**Comment by mrchrisoliver** [comment]
I hope I've included them correctly, creating issues on Github is fairly new to me.

The title for the 404 page actually says "Valet - Not Found" so it could be a Laravel Valet config interfering.

`{"level":"info","ts":1602268447.623755,"msg":"using provided configuration","config_file":"/Users/chris/Library/Application Support/Valet Lite/Caddyfile","config_adapter":""}
{"level":"info","ts":1602268447.635527,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
{"level":"error","ts":1602268447.63678,"logger":"tls","msg":"migrating certificates","error":"listing used ACME CAs: open /Users/chris/Library/Application Support/Caddy/acme: permission denied"}
{"level":"info","ts":1602268447.6371078,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
{"level":"info","ts":1602268447.638046,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0006fd8f0"}
run: loading initial config: loading new config: http app module: start: tcp: listening on :80: listen tcp :80: bind: address already in use`

`127.0.0.1 localhost penguin.example
255.255.255.255 broadcasthost
::1 localhost
127.0.0.1 kubernetes.docker.internal
1.amazonaws.com`

`http://penguin.example {
  reverse_proxy localhost:9001

  log {
    output file /Users/chris/.lite/log/penguin.example.log 
    format console
    level INFO
  }`

`{
	"caddyProcessId": 19779,
	"activated": true,
	"licenseKey": "HYQA-VFVZ-9HLW-VYQG-ZFX",
	"installed": true,
	"sites": [
		{
			"uuid": "803a8020-0a49-11eb-953d-69faf094ed05",
			"name": "penguin",
			"path": "/Users/Chris/Documents/Code/penguin",
			"isRunning": true,
			"port": 9001,
			"tld": "example",
			"url": "http://penguin.example",
			"processId": 19781,
			"type": "laravel",
			"logPath": "/Users/chris/.lite/log/penguin.example.log"
		}
	],
	"defaultTLD": "example",
	"caddyTrusted": true,
	"openSiteInBrowserWhenStarting": true
}`

**Comment by davidhemphill** [comment]
There appears to be a server already started on port 80. This is probably your Valet CLI setup still running when Valet Lite is trying to run. :-)

**Comment by davidhemphill** [comment]
Closing for now, but if you are absolutely sure no other web servers are running, let's reopen and take another look. :-)

**Comment by mikeerickson** [comment]
@davidhemphill can `valet` or `valet lite` be configured to use another default port? 

One thing I have noticed, with `valet lite` working on port 9000, this will conflict with `xdebug` as its default port is 9000

Perhaps you could configure to use a different starting port, even something like 9500

**Comment by davidhemphill** [comment]
Pushing an update tomorrow that will allow you to set the start port number for the web servers. 👍
