### ISSUE TITLE
Static site built with Jigsaw wont load

### ISSUE THREAD

**Issue by zaherg** [valet-lite/beta#20]
Hey David,

I have a site which is built using https://jigsaw.tighten.co but it wont work, it always complains about missing the artisan file

**Caddyfile**
```caddy
http://zah.me.test {
  reverse_proxy localhost:9001

  log {
    output file /Users/zaher/.lite/log/zah.me.test.log 
    format console
    level INFO
  }
}
```
[zah.me-log.txt](https://github.com/valet-lite/beta/files/5369637/zah.me-log.txt)
[caddy.txt](https://github.com/valet-lite/beta/files/5369639/caddy.txt)

**config.json**
```json
{
        "caddyProcessId": 71666,
        "installed": true,
        "activated": true,
        "licenseKey": "xxxxxxxxxxxxxxX",
        "sites": [
                {
                        "uuid": "d11e74f0-0d24-11eb-8556-5986c1f8f9bd",
                        "name": "zah.me",
                        "path": "/Users/zaher/Sites/workspace/zah.me",
                        "isRunning": true,
                        "port": 9001,
                        "tld": "test",
                        "url": "http://zah.me.test",
                        "processId": 71668,
                        "logPath": "/Users/zaher/.lite/log/zah.me.test.log"
                }
        ],
        "caddyTrusted": true
}
```
and I can confirm that caddy was running

**Comment by davidhemphill** [comment]
Valet Lite doesn't currently support Jigsaw static sites, but I'd love to add support for them. You should've been notified of the incompatible project type, however, so I'll add it as a bug. Thanks for reporting!

**Comment by zaherg** [comment]
I didn't get any notification from the app at all, I eve tried to point out to my static generated files but didn't work too

**Comment by davidhemphill** [comment]
I just added support for Jigsaw sites and it'll be available in the next release! 👍 

Sites are now expected to be Laravel, WordPress, Jigsaw, or static HTML/PHP, so no "incompatible type" errors should really be needed.
