### ISSUE TITLE
Support for non-laravel projects

### ISSUE THREAD

**Issue by denniseilander** [valet-lite/beta#24]
It would be nice to have support for non-laravel applications.
So just that plain php or even plain html projects are working too.

Now a `HTTP ERROR 502` error will be thrown if opening such projects in the browser. 
The error log contains the following line: `Could not open input file: artisan`.

**Comment by davidhemphill** [comment]
I just added support for plain PHP projects and it should be coming in the next update. 👍

**Comment by denniseilander** [comment]
@davidhemphill Nice work, thanks!
