### ISSUE TITLE
Updated to 0.2.0, now redirects to Verizon for Site

### ISSUE THREAD

**Issue by jjrohrer** [valet-lite/beta#26]
Right-clicking on "open site in browser" for "tall2.test" (and other sites) gets redirected to stupid Verizon dns search page (Verizon is my local ISP)
Right-clicking on "open php server in browser" for "tall2.test" opens the site seemingly fine (and it opens as http://127.0.0.1:9502 in the address bar).

Valet-lite seemed to be working before the last update, but that might have been a coincidence. I'm using Valet-lite because my local machine configure is a little confused and normal Valet-cli has also been opening sites to Verizon.

BTW - I love the app - keep it up.

**Comment by davidhemphill** [comment]
Sounds like the server is working correctly, but the Caddy server is being blocked by something else running on port 80. Is it possible that you have any other servers running?

**Comment by davidhemphill** [comment]
Gonna close this for now, but if you can verify you don't have any other web servers running on port 80, or can provide some other way of demonstrating this issue, please let me know. :-)
