### ISSUE TITLE
No progress/feedback when installing dependencies

### ISSUE THREAD

**Issue by edwinheij** [valet-lite/beta#3]
I don't know what's going on now. is it ready or not?
After entering my local password nothing is happening.

**Comment by mpociot** [comment]
@davidhemphill FYI, that's the error that I get:

![image](https://user-images.githubusercontent.com/804684/95471738-89f70d80-0982-11eb-851f-26c5f819167d.png)

**Comment by davidhemphill** [comment]
Just sent an email out to everyone. I sent only the link to the DMG, not the whole PKG file. :-) Should be good to go after you get all of those dependencies.
