### ISSUE TITLE
Complete uninstall

### ISSUE THREAD

**Issue by ricardomartos** [valet-lite/beta#30]
I want to uninstall it completely but I need to delete residual files. Could you tell me if you have a script to delete all of those?

**Comment by davidhemphill** [comment]
Sure! To uninstall, you can run these commands in your Terminal (or delete them with Finder):

```sh
rm /Applications/Valet\ Lite
rm -rf /Applications/Valet
sudo rm /etc/sudoers.d/lite
rm -rf ~/Library/Application\ Support/Valet\ Lite
```
