### ISSUE TITLE
Unable to quit the app via CMD-Q when no dependency library is available

### ISSUE THREAD

**Issue by mpociot** [valet-lite/beta#5]
As the title says. I have to exit the app using the dock to close it

**Comment by edwinheij** [comment]
Only the red close button in the app works with me.

**Comment by timrspratt** [comment]
@edwinheij the red close will only close the window, not the app.

The link in the mac menu (top left) also doesn't quit the app

**Comment by edwinheij** [comment]
@timrspratt Ah, you're right! Indeed.

**Comment by davidhemphill** [comment]
Hmm, weird. I'm able to use the shortcut and close the app via the window.

**Comment by mpociot** [comment]
If I close the window via the red close button and then press CMD+Q I get this error:

Uncaught Exception:
TypeError: Object has been destroyed
    at _ (/Applications/Valet Lite.app/Contents/Resources/app.asar/background.js:2:565622)
    at click (/Applications/Valet Lite.app/Contents/Resources/app.asar/background.js:2:568931)
    at MenuItem.click (electron/js2c/browser_init.js:1553:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1814:13)

**Comment by davidhemphill** [comment]
Ah, this seems to be a byproduct of the dependency library not being installed. Will need to add some feedback to the app in case it's not there.

**Comment by davidhemphill** [comment]
I added some in-app messaging to warn the user about a missing dependency library. 👍
