### ISSUE TITLE
Unable to manage license when no dependency library is available

### ISSUE THREAD

**Issue by timrspratt** [valet-lite/beta#6]
Clicking "Manage License" in the menu bar doesn't do anything.

OS: macOS Catalina (10.15.7)

**Comment by davidhemphill** [comment]
This also seems to be a byproduct of the dependency library not being installed. Will need to add some feedback to the app in case it's not there.

**Comment by davidhemphill** [comment]
I added some in-app messaging to warn the user about a missing dependency library. 👍
