### ISSUE TITLE
Stuck on setting page

### ISSUE THREAD

**Issue by c-fitzmaurice** [valet-lite/beta#7]
When clicking the settings cog and going to the settings page I cannot return the home page of the app. I tried clicking the cog multiple times but could only get back to it by closing the window and reopening.

![image](https://user-images.githubusercontent.com/3401771/95474380-083bbb80-0953-11eb-923d-ca27a300d72c.png)

**Comment by mpociot** [comment]
You have to click the "Valet Lite" typo - also took me a couple of tries :)
There should at least be a pointer cursor (and hover state) for this

**Comment by timrspratt** [comment]
On one of my apps (a tray menu one) I went for this approach..

1. Normal state (icon to manage settings)
<img width="319" alt="Screenshot 2020-10-08 at 16 04 46" src="https://user-images.githubusercontent.com/20431294/95477333-2370f000-0980-11eb-84d8-8ab3f6ca0877.png">

2. Settings state (button to return)
<img width="321" alt="Screenshot 2020-10-08 at 16 04 53" src="https://user-images.githubusercontent.com/20431294/95477344-266be080-0980-11eb-95bd-ee1202a49300.png">

On native apps, the concept of cursor changing isn't like it is for web, it's common to keep the pointer on links (it is accepted to change the hover state though)

**Comment by c-fitzmaurice** [comment]
Yes, @mpociot I see it now, the logo takes me back to the Home Screen. Thanks!

**Comment by davidhemphill** [comment]
I made an update today which changes the gear to a home icon to indicate you can click it to return to the main view. 👍

**Comment by c-fitzmaurice** [comment]
@davidhemphill You're the man, just hope it was a `wip` feature. ;)
