### ISSUE TITLE
Can the TLD be changed?

### ISSUE THREAD

**Issue by IvanG11** [valet-lite/beta#9]
I use Valet Lite at the same time with Laravel Valet both with *.test

If I start a site with valet lite, The page shows a 404 error because the domain is opened by Laravel Valet. The PHP server http://127.0.0.1:9001/ works well.

Is it possible to add in the UI to change the TLD?

**Comment by davidhemphill** [comment]
It would be fairly simple to add this as a global option, but would you be expecting it as a per-site option? That would probably require a new "site settings" view.

**Comment by IvanG11** [comment]
I think a global option is fine. I have never needed to use different TLDs.

**Comment by bezhanSalleh** [comment]
Ok, so i was getting this ERR_NAME_NOT_RESOLVED after the dependencies got installed.

I did a restart and a security pop up opened asking to allow caddy to handle incoming connections and et voila...
after that everything works as expected.

Suggestion:
I would remove the right click and add all of em as buttons, smallish compact buttons which removes one step and users are only one click away.

cheers mate

**Comment by davidhemphill** [comment]
Hey folks, I just added a preference to allow Valet Lite to open the site in your browser when you start its server. 👍
